# Generated by Django 4.2.4 on 2023-08-26 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_section_product_image_product_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='section',
        ),
        migrations.RemoveField(
            model_name='product_image',
            name='product',
        ),
        migrations.DeleteModel(
            name='Additional_Information',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Product_Image',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
