# Generated by Django 4.2.4 on 2023-09-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packaging_cost',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.IntegerField(null=True),
        ),
    ]
