# Generated by Django 4.2.4 on 2023-09-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_product_packaging_cost_product_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='packaging_cost',
            field=models.IntegerField(null=True),
        ),
    ]
