# Generated by Django 4.2.4 on 2023-09-03 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_product_packaging_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='packaging_cost',
            new_name='packing_cost',
        ),
    ]
